### ISSUE TITLE
插件自定义配置里面docs和root里面的path 是哪来的?

### ISSUE THREAD

**Issue by fengyulong113** [mingyuLi97/vite-plugin-vitepress-auto-sidebar#1]
插件自定义配置里面docs和root里面的path 是哪来的? 从“node”上引入还报错

**Comment by mingyuLi97** [comment]
就是 node 的内置包，参考[这里](https://github.com/mingyuLi97/blog/blob/master/docs/.vitepress/vite-config.ts#L1)
