### ISSUE TITLE
能否兼容一下 gitbook 的 `SUMMARY.md` ?

### ISSUE THREAD

**Issue by ykla** [mingyuLi97/vite-plugin-vitepress-auto-sidebar#2]
即完全通过 `SUMMARY.md`  来定义目录的生成。

示例：

```
## A

* [溯因 abduction (Igor Douven)](a/su-yin-abduction-igor-douven.md)
* [彼得·阿伯拉尔 Abelard \[Abailard\], Peter (Peter King and Andrew Arlig)](a/bi-de-abo-la-er-abelard-abailard-peter-peter-king-and-andrew-arlig.md)
* [\*偶然属性——见本质属性与偶然属性 accidental properties — see essential vs. accidental properties](a/ou-ran-shu-xing-jian-ben-zhi-shu-xing-yu-ou-ran-shu-xing-accidental-properties-see-essential-vs.-acc.md)
* [行动 action (Juan S. Piñeros Glasscock and Sergio Tenenbaum)](a/hang-dong-action-juan-s.-pieros-glasscock-and-sergio-tenenbaum/README.md)
  * [\*共同——见行为体：共享行为体 joint — see agency: shared](a/hang-dong-action-juan-s.-pieros-glasscock-and-sergio-tenenbaum/gong-tong-jian-neng-dong-xing-gong-xiang-neng-dong-xing-joint-see-agency-shared.md)
  * [\*逻辑 ——见逻辑学：行动的逻辑 logic of — see logic: action](a/hang-dong-action-juan-s.-pieros-glasscock-and-sergio-tenenbaum/luo-ji-jian-luo-ji-xue-hang-dong-de-luo-ji-logic-of-see-logic-action.md)
* [基于行动的知觉理论 action-based theories of perception (Robert Briscoe, Rick Grush, and Alison Springle)](a/ji-yu-hang-dong-de-zhi-jue-li-lun-actionbased-theories-of-perception-robert-briscoe-rick-grush-and-a.md)
* [\*超距作用——见量子力学：量子力学中的超距作用 action at a distance — see quantum mechanics: action at a distance in](a/chao-ju-zuo-yong-jian-liang-zi-li-xue-liang-zi-li-xue-zhong-de-chao-ju-zuo-yong-action-atadistance-s.md)
```

非常感谢你。

**Comment by mingyuLi97** [comment]
什么场景下使用，从 gitbook 迁移到 vitepress？ 还是想有个类似的功能（通过 summary 定义目录）？

**Comment by ykla** [comment]
> 什么场景下使用，从 gitbook 迁移到 vitepress？ 还是想有个类似的功能（通过 summary 定义目录）？

gitbook 可以自动创建并管理目录。通过 git action 就可以自动同步到另一个项目然后再使用  GitHub page  或服务器就非常方便了。同时也方便了迁移。

目前 gitbook 会窜改 markdown 文本，所以这个东西看起来只适合一开始把目录创建好，而且这个平台目前对于我的文档看起来无法处理了，文本量太大了。所以现在需要使用一个更快的平台。

我之前用 vuepress 都是手动改的，效率太低了，对于少量文本还能处理。但是 vitepress 不支持从目录自动提取 H1 做标题，强制要求写一个 text，不能单独只把路径在侧边栏配置文件中。

**Comment by mingyuLi97** [comment]
> > 什么场景下使用，从 gitbook 迁移到 vitepress？ 还是想有个类似的功能（通过 summary 定义目录）？
> 
> gitbook 可以自动创建并管理目录。通过 git action 就可以自动同步到另一个项目然后再使用 GitHub page 或服务器就非常方便了。同时也方便了迁移。
> 
> 目前 gitbook 会窜改 markdown 文本，所以这个东西看起来只适合一开始把目录创建好，而且这个平台目前对于我的文档看起来无法处理了，文本量太大了。所以现在需要使用一个更快的平台。
> 
> 我之前用 vuepress 都是手动改的，效率太低了，对于少量文本还能处理。但是 vitepress 不支持从目录自动提取 H1 做标题，强制要求写一个 text，不能单独只把路径在侧边栏配置文件中。

如果将内容（文件夹、文件）按照此插件约束的格式放置是不是能解决你说的问题, 不一定非要通过` SUMMARY.md` 这种文件来约束，这样反而会多声明一遍。

```
├── .vitepress
├── 溯因 abduction (Igor Douven).md
├── 行动 action (Juan S. Piñeros Glasscock and Sergio Tenenbaum)
│   ├── 共同——见行为体：共享行为体 joint — see agency: shared.md
│   └── 逻辑 ——见逻辑学：行动的逻辑 logic of — see logic: action.md
├── index.md
├── node_modules
└── package.json
```

**Comment by ykla** [comment]
> > > 什么场景下使用，从 gitbook 迁移到 vitepress？ 还是想有个类似的功能（通过 summary 定义目录）？
> > 
> > gitbook 可以自动创建并管理目录。通过 git action 就可以自动同步到另一个项目然后再使用 GitHub page 或服务器就非常方便了。同时也方便了迁移。
> > 
> > 目前 gitbook 会窜改 markdown 文本，所以这个东西看起来只适合一开始把目录创建好，而且这个平台目前对于我的文档看起来无法处理了，文本量太大了。所以现在需要使用一个更快的平台。
> > 
> > 我之前用 vuepress 都是手动改的，效率太低了，对于少量文本还能处理。但是 vitepress 不支持从目录自动提取 H1 做标题，强制要求写一个 text，不能单独只把路径在侧边栏配置文件中。
> 
> 如果将内容（文件夹、文件）按照此插件约束的格式放置是不是能解决你说的问题, 不一定非要通过` SUMMARY.md` 这种文件来约束，这样反而会多声明一遍。
> 
> ```
> ├── .vitepress
> ├── 溯因 abduction (Igor Douven).md
> ├── 行动 action (Juan S. Piñeros Glasscock and Sergio Tenenbaum)
> │   ├── 共同——见行为体：共享行为体 joint — see agency: shared.md
> │   └── 逻辑 ——见逻辑学：行动的逻辑 logic of — see logic: action.md
> ├── index.md
> ├── node_modules
> └── package.json
> ```

实际上现在是要从 gitbook 进行迁移。我已经通过 `SUMMARY.md` 定义了一遍。改 `SUMMARY.md` 也远比改 vitepress 的配置方便和简单直观，因为他就是普通的 markdown 格式，不存在一大堆嵌套关系和特殊的标点符号要求。而且可以指定顺序和前后关系，并且随意调整和目录无关。

**Comment by mingyuLi97** [comment]
如果定义了`SUMMARY.md`，何不直接定义官方给出的 sidebar。已经决定迁移，那么建议摒弃 gitbook 的写法，使用 vitepress
